# Snapfood Comments Analysis

In [17]:
with open(r"C:\Users\Behzad\Documents\project\snapfood\snapfood.csv", encoding="utf-8") as f:
    for _ in range(20):
        print(f.readline())

	comment	label	label_id

	واقعا حیف وقت که بنویسم سرویس دهیتون شده افتضاح	SAD	1

	قرار بود ۱ ساعته برسه ولی نیم ساعت زودتر از موقع رسید، شما ببین چقدرررررررررررر پلاک خفنههههه، من سالهاست مشتریشونم و سالهاست مزه بهشت میده غذاشون	HAPPY	0

	قیمت این مدل اصلا با کیفیتش سازگاری نداره، فقط ظاهر فریبنده داره، پرش میکنن کالباس و قارچ	SAD	1

	عالللی بود همه چه درست و به اندازه و کیفیت خوب، امیداورم همیشه کیفیتتون خوب باشه ما مشتری همیشگی بشیم	HAPPY	0

	شیرینی وانیلی فقط یک مدل بود.	HAPPY	0

	بدترین پیتزایی که تا به حال خورده بودم	SAD	1

	از همه لحاظ عالی ممنونم	HAPPY	0

	کیفیت غذا متوسط رو به پایین بود انگار داخل یه رستوران معمولی غذا خوردی درحالی که امتیاز رستوران در اسنپ فود ۴٫۳ بود	SAD	1

	همه اقلام تازه و به روز وخیلیییییی سریع بدستم رسید واقعا متشکرم	HAPPY	0

	همه چی خوب ولی هات داگ دورش کلا سوخته بود و داخلش خام بود!!!!	SAD	1

	اکلر فوق العاده بود اما بافت چیزکیک مونده بود و دوست نداشتم.	HAPPY	0

	خوب بود و از رستوران غنچه و اسنپ فود تشکر میکنم	HAPPY	0

	مثل همیشه عااااالی هستی پرپروک جاااااان مچکریم ازت	HAPPY	0

	Kheili khub bud mersi vaghan	HAPPY	0

	عکس با شیریبی که ارسال کردند فرق داشت و خیلی نامرتب و خورد شده بود. اصلا پیشنهاد نمیکنم	SAD	1

	سریع سفارش بدستم رسید ممنونم اسنپ فود	HAPPY	0

	خیلی عالی بود خیلی هم زود رسید خوشمزه	HAPPY	0

	هات داگ یکم خام بود. حجمش خوب بود	HAPPY	0

	ممنون که به صلاحدید هودتون سفارش رو تغییر دادید.	SAD	1

In [18]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Behzad\Documents\project\snapfood\snapfood.csv", sep="\t" ,encoding="utf-8")
df.head(10)

,Unnamed: 0,comment,label,label_id
0,NaN,واقعا حیف وقت که بنویسم سرویس دهیتون شده افتضاح,SAD,1.0
1,NaN,قرار بود ۱ ساعته برسه ولی نیم ساعت زودتر از مو...,HAPPY,0.0
2,NaN,قیمت این مدل اصلا با کیفیتش سازگاری نداره، فقط...,SAD,1.0
3,NaN,عالللی بود همه چه درست و به اندازه و کیفیت خوب...,HAPPY,0.0
4,NaN,شیرینی وانیلی فقط یک مدل بود.,HAPPY,0.0
5,NaN,بدترین پیتزایی که تا به حال خورده بودم,SAD,1.0
6,NaN,از همه لحاظ عالی ممنونم,HAPPY,0.0
7,NaN,کیفیت غذا متوسط رو به پایین بود انگار داخل یه ...,SAD,1.0
8,NaN,همه اقلام تازه و به روز وخیلیییییی سریع بدستم ...,HAPPY,0.0
9,NaN,همه چی خوب ولی هات داگ دورش کلا سوخته بود و دا...,SAD,1.0

In [19]:
df = df.drop(columns= ["Unnamed: 0"])
df.head()

                                             comment  label  label_id
0    واقعا حیف وقت که بنویسم سرویس دهیتون شده افتضاح    SAD       1.0
1  قرار بود ۱ ساعته برسه ولی نیم ساعت زودتر از مو...  HAPPY       0.0
2  قیمت این مدل اصلا با کیفیتش سازگاری نداره، فقط...    SAD       1.0
3  عالللی بود همه چه درست و به اندازه و کیفیت خوب...  HAPPY       0.0
4                      شیرینی وانیلی فقط یک مدل بود.  HAPPY       0.0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   comment   70000 non-null  object
 1   label     70000 non-null  object
 2   label_id  69480 non-null  float64
dtypes: float64(1), object(2)
memory usage: 1.6+ MB

In [21]:
# df["tokens"] = df["comment"].str.split()
df["tokens"] = df["comment"].apply(lambda x: x.split())
df[["comment", "tokens"]].head()

,comment,tokens
0,واقعا حیف وقت که بنویسم سرویس دهیتون شده افتضاح,"[واقعا, حیف, وقت, که, بنویسم, سرویس, دهیتون, ش..."
1,قرار بود ۱ ساعته برسه ولی نیم ساعت زودتر از مو...,"[قرار, بود, ۱, ساعته, برسه, ولی, نیم, ساعت, زو..."
2,قیمت این مدل اصلا با کیفیتش سازگاری نداره، فقط...,"[قیمت, این, مدل, اصلا, با, کیفیتش, سازگاری, ند..."
3,عالللی بود همه چه درست و به اندازه و کیفیت خوب...,"[عالللی, بود, همه, چه, درست, و, به, اندازه, و,..."
4,شیرینی وانیلی فقط یک مدل بود.,"[شیرینی, وانیلی, فقط, یک, مدل, بود.]"

In [22]:
df["tokens_unique"] = df["tokens"].apply(lambda x: list(set(x)))
df[["comment", "tokens_unique"]].head()

,comment,tokens_unique
0,واقعا حیف وقت که بنویسم سرویس دهیتون شده افتضاح,"[بنویسم, شده, حیف, افتضاح, واقعا, وقت, دهیتون,..."
1,قرار بود ۱ ساعته برسه ولی نیم ساعت زودتر از مو...,"[مشتریشونم, نیم, مزه, ببین, پلاک, من, سالهاست,..."
2,قیمت این مدل اصلا با کیفیتش سازگاری نداره، فقط...,"[فریبنده, اصلا, ظاهر, پرش, قارچ, فقط, این, کال..."
3,عالللی بود همه چه درست و به اندازه و کیفیت خوب...,"[بشیم, چه, همه, ما, به, درست, بود, اندازه, همی..."
4,شیرینی وانیلی فقط یک مدل بود.,"[یک, بود., شیرینی, فقط, مدل, وانیلی]"

In [23]:
happy_comments = df[df["label"] == "HAPPY"]["tokens_unique"]
sad_comments = df[df["label"] == "SAD"]["tokens_unique"]

In [25]:
from itertools import chain
happy_words = list(chain.from_iterable(happy_comments))
sad_words = list(chain.from_iterable(sad_comments))

In [26]:
from collections import Counter
happy_counter = Counter(happy_words)
sad_counter = Counter(sad_words)
top50_happy = happy_counter.most_common(50)
top50_sad = sad_counter.most_common(50)
print("Top 50 Happy Words: ")
for word, count in top50_happy:
    print(f"{word}: {count}")

Top 50 Happy Words:
و: 17487
بود: 16566
عالی: 9422
خیلی: 8878
خوب: 8709
به: 8319
از: 7832
هم: 6451
که: 6042
کیفیت: 5626
بود.: 5146
غذا: 5127
با: 5121
ولی: 5034
خوشمزه: 4623
ممنون: 4093
فقط: 3647
در: 3644
بسیار: 3388
همیشه: 3199
سفارش: 3163
رسید: 3126
شده: 3067
رو: 2952
این: 2950
تازه: 2892
من: 2780
مثل: 2624
واقعا: 2570
طعم: 2561
همه: 2540
پیک: 2419
پیتزا: 2316
سریع: 2279
گرم: 2263
ارسال: 2222
کم: 1986
اما: 1960
بود،: 1873
موقع: 1827
بسته: 1728
نبود: 1690
یه: 1678
برای: 1576
اسنپ: 1557
سرد: 1477
سیب: 1447
یک: 1439
بندی: 1437
ممنونم: 1388

In [27]:
print("\nTop 50 Sad Words: ")
for word, count in top50_sad:
    print(f"{word}: {count}")

Top 50 Sad Words:
و: 18463
بود: 17637
که: 9838
به: 9746
از: 9056
غذا: 7064
کیفیت: 6916
هم: 6796
خیلی: 6724
با: 6396
سفارش: 6341
شده: 6078
این: 5235
اصلا: 4991
بود.: 4888
در: 4765
من: 4640
رو: 4469
سرد: 4407
ولی: 4292
نبود: 3967
بسیار: 3792
پیتزا: 3701
واقعا: 3604
بد: 3512
خوب: 3423
یک: 2906
کاملا: 2891
مرغ: 2684
ارسال: 2639
بی: 2593
تا: 2489
کم: 2406
برای: 2403
مزه: 2241
متاسفانه: 2239
یه: 2222
تحویل: 2208
سیب: 2160
فقط: 2112
پایین: 2077
طعم: 2074
بودم: 1950
دیگه: 1897
اما: 1890
نداشت: 1862
رسید: 1827
قیمت: 1823
دادم: 1802
داده: 1790

In [28]:
import hazm
print("Hazm imported")

Hazm imported

In [29]:
from hazm import Normalizer, word_tokenize, stopwords_list
stop_words = set(stopwords_list())
happy_filterred = [word for word in happy_words if word not in stop_words]
sad_filterred = [word for word in sad_words if word not in stop_words]

In [32]:
happy_freq = Counter(happy_filterred)
sad_freq = Counter(sad_filterred)
top50_happy = happy_freq.most_common(50)
top50_sad = sad_freq.most_common(50)
print("\nTop 50 most frequent HAPPY words")
for word, count in top50_happy:
    print(f"{word}: {count}")

Top 50 most frequent HAPPY words
کیفیت: 5626
بود.: 5146
غذا: 5127
خوشمزه: 4623
ممنون: 4093
سفارش: 3163
تازه: 2892
واقعا: 2570
طعم: 2561
پیک: 2419
پیتزا: 2316
سریع: 2279
گرم: 2263
ارسال: 2222
بود،: 1873
موقع: 1827
بسته: 1728
یه: 1678
اسنپ: 1557
سرد: 1477
سیب: 1447
ممنونم: 1388
راضی: 1361
بودم: 1338
سس: 1303
خوش: 1259
تحویل: 1258
حجم: 1245
دستم: 1236
قیمت: 1233
مرغ: 1231
نان: 1193
تشکر: 1192
داغ: 1178
مزه: 1161
فود: 1110
زمان: 1049
رستوران: 1012
رسید.: 1006
سلام: 1000
زمینی: 982
زود: 954
ساندویچ: 933
…: 928
اصلا: 916
چی: 913
باشه: 847
العاده: 846
یکم: 844
مرسی: 844

In [33]:
print("\nTop 50 most frequent SAD words")
for word, count in top50_sad:
    print(f"{word}: {count}")

Top 50 most frequent SAD words
غذا: 7064
کیفیت: 6916
سفارش: 6341
اصلا: 4991
بود.: 4888
سرد: 4407
پیتزا: 3701
واقعا: 3604
بد: 3512
مرغ: 2684
ارسال: 2639
مزه: 2241
یه: 2222
تحویل: 2208
سیب: 2160
پایین: 2077
طعم: 2074
بودم: 1950
دیگه: 1897
نداشت: 1862
قیمت: 1823
دادم: 1802
پیک: 1780
بود،: 1776
ساعت: 1766
رستوران: 1720
نان: 1699
مونده: 1670
سس: 1614
حجم: 1607
بسته: 1556
زمینی: 1524
نون: 1450
تازه: 1443
گوشت: 1416
پنیر: 1412
ساندویچ: 1353
خشک: 1333
…: 1195
راضی: 1193
شیرینی: 1176
نبود.: 1167
تاخیر: 1150
اسنپ: 1137
ریخته: 1134
سالاد: 1130
سوخته: 1106
کباب: 1101
کیک: 1096
سلام: 1085

In [38]:
top50_happy_words = [word for word, _ in top50_happy]
top50_sad_words = [word for word, _ in top50_sad]
print("top 50 HAPPY words")
print(top50_happy_words)

top 50 HAPPY words
['کیفیت', 'بود.', 'غذا', 'خوشمزه', 'ممنون', 'سفارش', 'تازه', 'واقعا', 'طعم', 'پیک', 'پیتزا', 'سریع', 'گرم', 'ارسال', 'بود،', 'موقع', 'بسته', 'یه', 'اسنپ', 'سرد', 'سیب', 'ممنونم', 'راضی', 'بودم', 'سس', 'خوش', 'تحویل', 'حجم', 'دستم', 'قیمت', 'مرغ', 'نان', 'تشکر', 'داغ', 'مزه', 'فود', 'زمان', 'رستوران', 'رسید.', 'سلام', 'زمینی', 'زود', 'ساندویچ', '…', 'اصلا', 'چی', 'باشه', 'العاده', 'یکم', 'مرسی']

In [39]:
print("top 50 SAD words")
print(top50_sad_words)

top 50 SAD words
['غذا', 'کیفیت', 'سفارش', 'اصلا', 'بود.', 'سرد', 'پیتزا', 'واقعا', 'بد', 'مرغ', 'ارسال', 'مزه', 'یه', 'تحویل', 'سیب', 'پایین', 'طعم', 'بودم', 'دیگه', 'نداشت', 'قیمت', 'دادم', 'پیک', 'بود،', 'ساعت', 'رستوران', 'نان', 'مونده', 'سس', 'حجم', 'بسته', 'زمینی', 'نون', 'تازه', 'گوشت', 'پنیر', 'ساندویچ', 'خشک', '…', 'راضی', 'شیرینی', 'نبود.', 'تاخیر', 'اسنپ', 'ریخته', 'سالاد', 'سوخته', 'کباب', 'کیک', 'سلام']

In [40]:
df_words = pd.DataFrame({"Happy_Words": top50_happy_words, "Sad_Words": top50_sad_words})
print(df_words.head(10))

  Happy_Words Sad_Words
0       کیفیت       غذا
1        بود.     کیفیت
2         غذا     سفارش
3      خوشمزه      اصلا
4       ممنون      بود.
5       سفارش       سرد
6        تازه     پیتزا
7       واقعا     واقعا
8         طعم        بد
9         پیک       مرغ

In [42]:
df_words.to_csv(r"C:\Users\Behzad\Documents\project\snapfood\top_50_words.csv", index=False, encoding="utf-8-sig")